version: '3.3'

services:
  composer:
    image: tnhnclskn/composer
    command:
      - install
    volumes:
      - ./backend:/var/www/html
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure

  php:
    image: tnhnclskn/symfony
    volumes:
      - ./backend:/var/www/html
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  web:
    image: nginx
    networks:
      - default
      - traefik-net
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - php
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:$HOSTNAME,www.$HOSTNAME
        traefik.docker.network: traefik-net
    configs:
      - source: nginx_vhost
        target: /etc/nginx/conf.d/default.conf

  pma:
    image: phpmyadmin/phpmyadmin
    networks:
      - default
      - traefik-net
    depends_on:
      - db
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:pma.$HOSTNAME
        traefik.docker.network: traefik-net

configs:
  nginx_vhost:
    file: ./config/vhost.conf

networks:
  traefik-net:
    external:
      name: traefik-net

volumes:
  mysql_data:
